### ISSUE TITLE
you can STILL add other attributes, eg style, using inspect element

### ISSUE THREAD

**Issue by glacialcascade** [ElementalCode/elemental#243]
Basically there are a lot of attributes that arent in the dropdown, you can acces them with Inspect element

**Comment by matthewr6** [comment]
Not an issue, IMO.  If you can do that, you're probably not Elemental's target audience anyways :P  @ElementalCode/programmers Thoughts?

**Comment by TheInitializer** [comment]
why is that a problem

**Comment by matthewr6** [comment]
The real problem is that we don't have enough attributes available :P

**Comment by TheInitializer** [comment]
:point_up:

**Comment by TheInitializer** [comment]
Just add all the possible attributes, or a few basic ones and a text box to enter your own, and it will become even less of a problem :package:

**Comment by matthewr6** [comment]
@TheInitializer 
https://github.com/ElementalCode/elemental/blob/78714abe8734b3a4c85bd074cecbd72e5485aa17/apps/projects/static/js/editor/files.js#L58

**Comment by TheInitializer** [comment]
lol. problem is not all of those apply to every element (`<strong href="bobby.com">`?)

**Comment by matthewr6** [comment]
You can put them on every element, though :P

**Comment by mrjacobbloom** [comment]
> You can put them on every element, though :P

We shouldn't just limit the available attributes to what's applicable. I'd rather give the user all of them and force them to learn what they actually do.

Also it's less work on our end

**Comment by joker314** [comment]
I think that you should give bad attribute blocks a yellow-ish border, and a ⚠️ symbol is placed to the right of the block. When you click it, it shows you a picture of what you might mean, and what the attribute is usually used for, and if you click "Change" then it automatically replaces it.

For example, `img ( [href] = [google.com] )` then it might replace it with

```
a ( [href] = [google.com] ){
  img
}
```
and then put a warning on the inner block, saying that according to the spec you need an alt and src attribute. When you click on the warning, it might change it to
```
 img (src = ?) (alt = ?)
```
so that you can edit it.

I think this system would work best.

###### Also, could you please make the z-index of blocks that are currently being dragged very high, so that they appear above other blocks as well as on-top of the block pallet.

Sorry for intruding on your project.

**Comment by mrjacobbloom** [comment]
> ###### Also, could you please make the z-index of blocks that are currently being dragged very high, so that they appear above other blocks as well as on-top of the block pallet.

We have that fixed in our staging ground, we just haven't pushed it to the main website yet

**Comment by joker314** [comment]
Ah, ok.

**Comment by mrjacobbloom** [comment]
Resolving since #245 added more attributes
