### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by matthewr6** [ElementalCode/elemental#3]
Bamboo, because I love bamboo?
Please?

:P

**Comment by PullJosh** [comment]
I had already decided on Elemental, because we had to pick something, and nobody seemed overly opinionated (plus, you did see [where the idea](https://scratch.mit.edu/discuss/topic/134554/?page=1#post-1215004) for "bamboo" came from, right?)

If anybody really has major issues with the name, we can try to adjust things, but I don't think it's that big a deal.

**Comment by matthewr6** [comment]
Oh, fine :P
