### ISSUE TITLE
How do we handle saving?

### ISSUE THREAD

**Issue by robinp7720** [ElementalCode/elemental#41]
Send each file individually to the backend via the rest api and save them in a temp folder and package them into a zip or folder once each file has been uploaded

or

Let the front end handle it and package each file into a zip and upload the file to the server. Then validate the content on the backend. (This would be personal choice as it would be easier front end and backend and would allow for complete offline saving of projects without needing to upload them)

**Comment by matthewr6** [comment]
Have two options - download locally, or save online (requiring an account - sending JSON data to the server, most likely via ajax since a page refresh is out of the question).  Both will be easy to implement once we figure out a way to parse JSON/HTML/CSS back and forth - I posted a few links to npm packages that we could use.

For CSS: https://github.com/aramk/CSSJSON
For HTML: https://www.npmjs.com/package/htmlparser2 and https://www.npmjs.com/package/htmlparser-to-html

so glad I learned Django instead of staying with PHP lol

**Comment by quat1024** [comment]
JSZip is worth mentioning - https://stuk.github.io/jszip/ - lets us create a .zip file and add items to it using plain JavaScript, without pinging a backend server or something

**Comment by matthewr6** [comment]
Yup, perfect for giving the option of downloading locally.

**Comment by robinp7720** [comment]
My idea was to have the spirtes plane a list of all the files and folders in the project. is this what you have in mind too?

**Comment by robinp7720** [comment]
I'd recommend to convert nothing to json or any other format as people would be using assets such as images in their project. Once offline saving to zip has been implemented, we can easily upload the zip file to the server aswell. The python backend for this might be a little more difficult. I've only ever handled file uploads with php.

**Comment by matthewr6** [comment]
We are only allowing external images.

**Comment by robinp7720** [comment]
I'd say we allow them as it is common practice to have your own image assets but maybe just not allow them to be uploaded? We could have an alert box alerting users that uploading images is not allowed and they would be automatically removed from the project.

**Comment by matthewr6** [comment]
Sounds good!
Please read through the issues, though - we've already decided on a lot of this stuff...

**Comment by matthewr6** [comment]
https://github.com/ElementalCode/Elemental/issues/27
